/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface ArtifactLink {
  from_artifact: string;
  kind: string;
  project_id: number;
  to_artifact: string;
}

export interface CaptureDelivery {
  at: string | null;
  chars: number | null;
  eligible: number | null;
  event: string | null;
  omitted: number | null;
  outcome: string | null;
  path: string | null;
  reason: string | null;
  session_id: string | null;
  units: string | null;
}

export interface CaptureEdit {
  observed_at: string | null;
  path: string | null;
  session_id: string | null;
  tool_event_id: string | null;
  turn_id: string | null;
  via: string | null;
}

export interface CaptureMessage {
  captured_at: string | null;
  content_hash: Buffer | null;
  created_at: string | null;
  external_id: string | null;
  original_bytes: number | null;
  redacted: number | null;
  session_id: string | null;
  speaker: string | null;
  text: string | null;
  truncated: number | null;
  turn_id: string | null;
}

export interface CaptureSession {
  branch: string | null;
  external_id: string | null;
  host: string | null;
  id: string | null;
  project_id: number | null;
  started_at: string | null;
}

export interface Delivery {
  at: string;
  chars: Generated<number>;
  eligible: Generated<number>;
  event: string;
  id: Generated<number>;
  omitted: Generated<number>;
  outcome: string;
  path: string | null;
  reason: string | null;
  session_id: string | null;
}

export interface DeliveryUnit {
  delivery_id: number;
  unit_id: number;
}

export interface EditObservation {
  id: Generated<number>;
  observed_at: string;
  path: string;
  session_id: string;
  tool_event_id: string | null;
  turn_id: string | null;
  via: string;
}

export interface ExternalReference {
  added_at: string;
  id: Generated<number>;
  owner_source_id: number;
  project_id: number;
  span_end: number;
  span_start: number;
  url: string;
}

export interface ExtractionRun {
  draft_id: string | null;
  finished_at: string | null;
  id: Generated<number>;
  input_bytes: number | null;
  origin: string;
  project_id: number;
  reason: string | null;
  session_id: string | null;
  started_at: string;
  status: string;
  target: string;
}

export interface FieldDef {
  added_at: string;
  description: string;
  enum_values: string | null;
  id: Generated<number>;
  kinds: Generated<string>;
  label: string;
  name: string;
  project_id: number;
  run_id: number;
  source_id: number;
  span_end: number;
  span_start: number;
  type: string;
}

export interface ForgetBatch {
  at: string;
  id: Generated<number>;
  project_id: number;
}

export interface OwnerIdentity {
  bound_at: string;
  external_id: string;
  login: string | null;
  provider: string;
}

export interface Project {
  created_at: Generated<string>;
  id: Generated<number>;
  key: string;
  name: string;
}

export interface Session {
  branch: string | null;
  external_id: string;
  host: string;
  id: string;
  project_id: number;
  started_at: string;
}

export interface Source {
  artifact: string;
  author_association: string | null;
  author_external_id: string | null;
  author_kind: string;
  author_login: string | null;
  available_at: string | null;
  blob_sha: string | null;
  captured_at: string;
  commit_sha: string | null;
  content_hash: Buffer;
  created_at: string;
  diff_hunk: string | null;
  event_kind: string | null;
  external_id: string;
  id: Generated<number>;
  indexed: number;
  kind: string;
  line_end: number | null;
  line_start: number | null;
  original_bytes: number;
  parent_external_id: string | null;
  path: string | null;
  project_id: number;
  redacted: Generated<number>;
  revision: number;
  session_id: string | null;
  text: string;
  truncated: Generated<number>;
  turn_id: string | null;
  url: string | null;
}

export interface SourceForgotten {
  artifact: string;
  batch_id: number;
  content_hash: Buffer;
  external_id: string;
  kind: string;
  project_id: number;
  revision: number;
  source_id: Generated<number>;
}

export interface SourceProcessing {
  outcome: string;
  run_id: number;
  source_id: number;
}

export interface SphicaGeneration {
  generation: number;
}

export interface Unit {
  content_hash: Buffer;
  created_at: string;
  extraction: string;
  extraction_reason: string | null;
  id: Generated<number>;
  key: string;
  kind: string;
  lifecycle: Generated<string>;
  no_code_surface: string | null;
  project_id: number;
  revision: Generated<number>;
  revisit_when: string | null;
  run_id: number;
  scope_note: string | null;
  stance: string | null;
  text: string;
  unsourced: Generated<number>;
  why: string | null;
}

export interface UnitAdoption {
  added_at: string;
  id: Generated<number>;
  retracted_at: string | null;
  retraction_reason: string | null;
  retraction_source_id: number | null;
  retraction_span_end: number | null;
  retraction_span_start: number | null;
  route: string;
  run_id: number;
  source_id: number;
  span_end: number;
  span_start: number;
  unit_id: number;
}

export interface UnitAlias {
  added_at: string;
  content_hash: Buffer;
  id: Generated<number>;
  run_id: number;
  terms: string;
  unit_id: number;
}

export interface UnitAnchor {
  added_at: string;
  commit_sha: string | null;
  edit_observation_id: number | null;
  excerpt: string | null;
  id: Generated<number>;
  line_end: number | null;
  line_start: number | null;
  path: string;
  replaced_by: number | null;
  retired_at: string | null;
  role: string;
  run_id: number;
  symbol: string | null;
  unit_id: number;
}

export interface UnitEvidence {
  added_at: string;
  id: Generated<number>;
  option_id: number | null;
  reported_speaker: string | null;
  retracted_at: string | null;
  retraction_reason: string | null;
  retraction_source_id: number | null;
  retraction_span_end: number | null;
  retraction_span_start: number | null;
  role: string;
  run_id: number;
  source_id: number;
  span_end: number;
  span_start: number;
  unit_id: number;
}

export interface UnitField {
  added_at: string;
  field_def_id: number;
  id: Generated<number>;
  run_id: number;
  source_id: number;
  span_end: number;
  span_start: number;
  unit_id: number;
  value: string;
}

export interface UnitLink {
  added_at: string;
  from_unit: number;
  kind: string;
  resolution: string | null;
  resolved_at: string | null;
  run_id: number;
  to_unit: number;
}

export interface UnitOption {
  id: Generated<number>;
  outcome: string;
  position: number;
  reconsider_when: string | null;
  text: string;
  unit_id: number;
  why: string | null;
}

export interface UnitSearchText {
  alias: string | null;
  body: string | null;
  id: number | null;
  ident: string | null;
}

export interface UnitState {
  at: string;
  forget_id: number | null;
  from_state: string | null;
  id: Generated<number>;
  reason: string;
  run_id: number | null;
  source_id: number | null;
  to_state: string;
  unit_id: number;
}

export interface UnitSupport {
  missing: string | null;
  unit_id: number | null;
}

export interface Work {
  branch: string | null;
  current: string;
  goal: string;
  id: Generated<number>;
  key: string;
  next: Generated<string>;
  project_id: number;
  run_id: number | null;
  status: string;
  title: string;
  updated_at: string;
}

export interface DB {
  artifact_link: ArtifactLink;
  capture_delivery: CaptureDelivery;
  capture_edit: CaptureEdit;
  capture_message: CaptureMessage;
  capture_session: CaptureSession;
  delivery: Delivery;
  delivery_unit: DeliveryUnit;
  edit_observation: EditObservation;
  external_reference: ExternalReference;
  extraction_run: ExtractionRun;
  field_def: FieldDef;
  forget_batch: ForgetBatch;
  owner_identity: OwnerIdentity;
  project: Project;
  session: Session;
  source: Source;
  source_forgotten: SourceForgotten;
  source_processing: SourceProcessing;
  sphica_generation: SphicaGeneration;
  unit: Unit;
  unit_adoption: UnitAdoption;
  unit_alias: UnitAlias;
  unit_anchor: UnitAnchor;
  unit_evidence: UnitEvidence;
  unit_field: UnitField;
  unit_link: UnitLink;
  unit_option: UnitOption;
  unit_search_text: UnitSearchText;
  unit_state: UnitState;
  unit_support: UnitSupport;
  work: Work;
}
